### ISSUE TITLE
给些建议

### ISSUE THREAD

**Issue by fantingsheng** [airen/DemoHouse#1]
应该对每个demo给个详细的介绍或者演示啥的

**Comment by airen** [comment]
@fantingsheng 大部分的每个示例都有对应的Readme文件，文件中附有相应的演示地址和教程地址。当然如果有同学能帮忙整一个自动化工具，根据添加的文件目录，生成一个首页。这样就更好了。

**Comment by cangku** [comment]
@airen 家里网络不好，clone失败。我复制目录做了一个[md](https://github.com/haystacks/blog/blob/b11c714b4e8a3ad744dc3c216021beaadee6f536/www.unofficial.cn/source/demo/promise/a.md)，然后在自己的[博客](http://www.unofficial.cn)弄了一个列表，http://www.unofficial.cn/2016/10/12/demohouse.html

**Comment by airen** [comment]
@cangku 这种方式还是需要人工去处理md文件，我在考虑是否有什么更智能的处理方式，每次添加了对应的demo进来了，就能读到相关数据。这样或许会好一些。另外放在站上，[w3cplus](http://www.w3cplus.com)上也可以放置，最终考虑放到这里，是想需要源码的同学，能很方便的获取。但没有考虑预览的事项。用户体验没做好。(^_^)

**Comment by airen** [comment]
谢谢 @cangku 提供的`index.js`，生成对应的`list.md`文件。在你的思路上，我创建了一个`index.html`，然后在库布了一个[https://airen.github.io/DemoHouse/](https://airen.github.io/DemoHouse/)，这样的话，就可以直接在这里访问，比如：https://airen.github.io/DemoHouse/2-blocks-template/。另外有同学提供一个：https://www.npmjs.com/package/markdown-to-html ，我晚上学习一下。

**Comment by airen** [comment]
@jerexyz 我在本地先操作

```
npm install
```

然后操作

```
npm start
```
结果报下面的错误信息：

```
> demo_house@1.0.0 start /Applications/XAMPP/xamppfiles/htdocs/workshop/DemoHouse
> gulp

/Applications/XAMPP/xamppfiles/htdocs/workshop/DemoHouse/gulpfile.js:26
            let demoFiles = files.filter(function (file) {
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at execute (/Applications/XAMPP/xamppfiles/htdocs/workshop/DemoHouse/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:35:18)
    at Liftoff.handleArguments (/Applications/XAMPP/xamppfiles/htdocs/workshop/DemoHouse/node_modules/gulp/node_modules/gulp-cli/index.js:149:63)
    at Liftoff.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/workshop/DemoHouse/node_modules/gulp/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! demo_house@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo_house@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the demo_house package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs demo_house
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls demo_house
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/XAMPP/xamppfiles/htdocs/workshop/DemoHouse/npm-debug.log
```

求 @jerexyz 指点。另外（安装的时候我用的`tnpm install`，使用`npm install`一直卡在一个地方）。

**Comment by jerexyz** [comment]
@airen  用node 6.7 以上的版本试下呢？

**Comment by airen** [comment]
@jerexyz 我再试试

**Comment by airen** [comment]
想做个分类和过滤，不知道大家有没有好的建议，和后续DEMO自动更新`index.html`

**Comment by cangku** [comment]
自动更新可以使用hook，我把index.js稍微修改了一下，作为shell执行，git commit时会自动更新生成list.md添加到本次提交中。@jerexyz 的也可以类似方法操作，暂时想到的是这个。分类过滤暂时没有好的想法

**Comment by cheogo** [comment]
如果能把效果，直接在外面预览出来，会直观很多。 例如：http://www.jq22.com/daima

**Comment by cangku** [comment]
@cheogo iframe下就可以了

**Comment by evolutionjay** [comment]
试试看
[Codekit](https://incident57.com/codekit/index.html) 这个app， 直接MD生成HTML

**Comment by sxgc** [comment]
能分门别类就好了

**Comment by airen** [comment]
@evolutionjay 现在首面可以生成出来，而且也方便。正如 @sxgc 所说，有个分类就更好了。昨天晚上和 @jerexyz 同学也聊到过这方面的事项。

我们讨论下来，看看后面有哪些方法可以对生成出来的`index.html`做一些功能上的优化：

- 添加分类标签
- 添加过滤功能
- DEMO展示相关信息，比如标题、简单描述、作者信息等
